'use client';
import {useEffect,useState} from 'react';
import * as XLSX from 'xlsx';
import {createClient} from '@supabase/supabase-js';
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
const clean=v=>String(v??'').trim().replace(/^'+/,'');
const hdr=(h,names)=>{const a=h.map(x=>String(x??'').trim().toLowerCase());for(const n of names){const i=a.indexOf(n.toLowerCase());if(i>=0)return i}return -1};
const codeFrom=d=>{const m=String(d??'').toUpperCase().match(/\b([A-Z]\d{3,4}[A-Z]?)\b/);return m?.[1]||''};
const variant=(d,name)=>{const s=String(d??'').toUpperCase();let m=s.match(/\b(\d{1,2})\s*\/\s*(\d{2,4})\s*GB\b/);if(!m)m=s.match(/\b(\d{1,2})\s*\/\s*(\d{2,4})\b/);return m?(`${name||codeFrom(d)} ${m[1]}/${m[2]}`).trim():(name||codeFrom(d)||'-')};
export default function Home(){
const[session,setSession]=useState(null),[role,setRole]=useState('viewer'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[dbFile,setDbFile]=useState(null),[checkFile,setCheckFile]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[stats,setStats]=useState(null);
useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
useEffect(()=>{if(session)supabase.from('profiles').select('role').eq('id',session.user.id).single().then(({data})=>setRole(data?.role||'viewer'))},[session]);
async function login(e){e.preventDefault();setMsg('');const email=username.trim().toLowerCase()==='admin'?'admin@imeimatcher.local':username.trim();const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message)}
async function logout(){await supabase.auth.signOut()}
async function uploadDb(){if(!dbFile)return;setBusy(true);setMsg('Membaca database...');try{const wb=XLSX.read(await dbFile.arrayBuffer());let rows=[];for(const s of wb.SheetNames){if(!/^([1-9])$/.test(s))continue;const a=XLSX.utils.sheet_to_json(wb.Sheets[s],{header:1,defval:''});if(!a.length)continue;const hi=hdr(a[0],['imei']);const hd=hdr(a[0],['item desc','item description','itemdesc']);for(const r of a.slice(1)){const imei=clean(r[hi]),desc=clean(r[hd]);if(/^\d{10,20}$/.test(imei)&&desc)rows.push({imei,item_desc:desc})}}if(!rows.length)throw new Error('Tidak ditemukan data IMEI pada sheet 1-9.');const{data:v,error:ve}=await supabase.from('database_versions').insert({file_name:dbFile.name,row_count:rows.length,status:'active'}).select().single();if(ve)throw ve;const batch=500;for(let i=0;i<rows.length;i+=batch){const part=rows.slice(i,i+batch).map(x=>({...x,database_version_id:v.id}));const{error}=await supabase.from('imei_database').insert(part);if(error)throw error}setMsg(`Database berhasil diupload: ${rows.length.toLocaleString()} IMEI.`)}catch(e){setMsg(e.message||String(e))}finally{setBusy(false)}}
async function check(){if(!checkFile)return;setBusy(true);setMsg('Mencocokkan IMEI...');try{const wb=XLSX.read(await checkFile.arrayBuffer());const ws=wb.Sheets[wb.SheetNames[0]],a=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});if(!a.length)throw new Error('File pemeriksaan kosong.');const hi=hdr(a[0],['imei']);if(hi<0)throw new Error('Kolom IMEI tidak ditemukan.');const imeis=a.slice(1).map(r=>clean(r[hi]));const{data,error}=await supabase.rpc('match_imeis',{p_imeis:imeis});if(error)throw error;const map=new Map((data||[]).map(x=>[clean(x.imei),x]));const out=[...a];if(!out[0][7])out[0][7]='Item Desc';if(!out[0][8])out[0][8]='Model / Variant';let found=0;for(let i=0;i<imeis.length;i++){const x=map.get(imeis[i]);if(x){out[i+1][7]=x.item_desc;out[i+1][8]=variant(x.item_desc,x.model)}else{out[i+1][7]='TIDAK DITEMUKAN';out[i+1][8]='TIDAK DITEMUKAN'}}found=(data||[]).length;const sh=XLSX.utils.aoa_to_sheet(out);const outwb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(outwb,sh,'hasil');XLSX.writeFile(outwb,`hasil_${checkFile.name}`);setStats({total:imeis.length,found,missing:imeis.length-found});setMsg('File hasil berhasil dibuat dan diunduh.')}catch(e){setMsg(e.message||String(e))}finally{setBusy(false)}}
if(!session)return <main><div className="card"><h1>IMEI Matcher</h1><p className="muted">Login admin</p><form onSubmit={login} className="grid"><input placeholder="Username" value={username} onChange={e=>setUsername(e.target.value)} required/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button type="submit">Masuk</button></form>{msg&&<p className="error">{msg}</p>}<p className="muted">Akun admin: username <b>admin</b></p></div></main>;
return <main><div className="row" style={{justifyContent:'space-between',alignItems:'center'}}><div><h1>IMEI Matcher</h1><p className="muted">Login sebagai {role}</p></div><button className="secondary" onClick={logout}>Keluar</button></div>{role==='admin'&&<div className="card"><h2>Update Database IMEI</h2><p className="muted">Upload Excel dengan sheet 1-9 yang memiliki kolom IMEI dan Item Desc.</p><div className="row"><input type="file" accept=".xlsx,.xls" onChange={e=>setDbFile(e.target.files?.[0]||null)}/><button onClick={uploadDb} disabled={busy||!dbFile}>Upload Database</button></div></div>}<div className="card"><h2>Cek IMEI</h2><p className="muted">Kolom IMEI dicocokkan secara exact. Hasil ditulis ke H (Item Desc) dan I (Model / Variant).</p><div className="row"><input type="file" accept=".xlsx,.xls" onChange={e=>setCheckFile(e.target.files?.[0]||null)}/><button onClick={check} disabled={busy||!checkFile}>Cek & Download</button></div>{stats&&<p className="ok">Total: {stats.total.toLocaleString()} · Ditemukan: {stats.found.toLocaleString()} · Tidak ditemukan: {stats.missing.toLocaleString()}</p>}</div>{msg&&<div className="card"><b>Status:</b> {msg}</div>}</main>}