'use client';
import {useEffect,useState} from 'react';
import * as XLSX from 'xlsx';
import {createClient} from '@supabase/supabase-js';
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
const clean=v=>String(v??'').trim().replace(/^'+/,'');
const hdr=(h,names)=>{const a=h.map(x=>String(x??'').trim().toLowerCase());for(const n of names){const i=a.indexOf(n.toLowerCase());if(i>=0)return i}return -1};
const codeFrom=d=>{const m=String(d??'').toUpperCase().match(/\b([A-Z]\d{3,4}[A-Z]?)\b/);return m?.[1]||''};
const modelName=d=>{const s=String(d??'').toUpperCase();const code=codeFrom(s);const map={'A047F':'A05-S','A057F':'A05-S','A065F':'A06','A066B':'A066','A075F':'A07','A076B':'A07','A176B':'A17','A175F':'A17','A276B':'A27','A376B':'A37','A576B':'A57','S948B':'S26 Ultra','F976':'Galaxy Z Fold8 Ultra','X133N':'TAB A11 Wifi','X135G':'TAB A11 5G','S731B':'Galaxy S25 FE','S741B':'Galaxy S26 FE 5G'};if(map[code])return map[code];if(/Z\s*FOLD\s*8\s*ULTRA|FOLD8\s*ULTRA/.test(s))return 'Galaxy Z Fold8 Ultra';if(/Z\s*FOLD\s*8/.test(s))return 'Galaxy Z Fold8 Wide';if(/Z\s*FLIP\s*8/.test(s))return 'Galaxy Z Flip8';if(/S26\s*ULTRA/.test(s))return 'S26 Ultra';if(/S26\+|S26 PLUS/.test(s))return 'S26+';if(/\bS26\b/.test(s))return 'S26';if(/TAB\s*A11/.test(s))return 'TAB A11 Wifi';return code||'-'};
const variant=(d,name)=>{const s=String(d??'').toUpperCase();const n=name||modelName(d);let m=s.match(/\b(\d{1,2})\s*\/\s*(\d{2,4})\s*GB\b/);if(!m)m=s.match(/\b(\d{1,2})\s*\/\s*(\d{2,4})\b/);if(m)return (\`${n} ${m[1]}/${m[2]}\`).trim();const up=s.match(/\b\d{2,4}GB\s+UP\s+(\d{2,4})GB\b/);if(up)return \`${n} ${up[1]}GB\`;return n};
export default function Home(){
const[session,setSession]=useState(null),[role,setRole]=useState('viewer'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[dbFile,setDbFile]=useState(null),[checkFile,setCheckFile]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[stats,setStats]=useState(null);
useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
useEffect(()=>{if(session)supabase.from('profiles').select('role').eq('id',session.user.id).single().then(({data})=>setRole(data?.role||'viewer'))},[session]);
async function login(e){e.preventDefault();setMsg('');const email=username.trim().toLowerCase()==='admin'?'admin@imeimatcher.local':username.trim();let{error}=await supabase.auth.signInWithPassword({email,password});if(error){const s=await supabase.auth.signUp({email,password,options:{data:{username}}});if(!s.error){const r=await supabase.auth.signInWithPassword({email,password});error=r.error}else error=s.error}if(error)setMsg(error.message)}
async function logout(){await supabase.auth.signOut()}
async function uploadDb(){if(!dbFile)return;setBusy(true);setMsg('Membaca database...');try{const wb=XLSX.read(await dbFile.arrayBuffer(),{cellDates:false});let rows=[];const sheetInfo=[];for(const s of wb.SheetNames){const a=XLSX.utils.sheet_to_json(wb.Sheets[s],{header:1,defval:'',raw:true});if(!a.length)continue;let headerRow=-1,hi=-1,hd=-1;for(let r=0;r<Math.min(a.length,20);r++){const row=a[r]||[];const imeiIdx=hdr(row,['imei','imei number','imei no','imei no.','imei1']);const descIdx=hdr(row,['item desc','item description','itemdesc','description','product description']);if(imeiIdx>=0&&descIdx>=0){headerRow=r;hi=imeiIdx;hd=descIdx;break}}if(headerRow<0){sheetInfo.push(`${s}: header IMEI/Item Desc tidak ditemukan`);continue}let count=0;for(const r of a.slice(headerRow+1)){const imei=clean(r[hi]);const desc=clean(r[hd]);if(/^\d{10,20}$/.test(imei)&&desc){rows.push({imei,item_desc:desc});count++}}sheetInfo.push(`${s}: ${count.toLocaleString()} IMEI`)}const unique=new Map();for(const x of rows)if(!unique.has(x.imei))unique.set(x.imei,x);rows=[...unique.values()];if(!rows.length)throw new Error(`Tidak ditemukan data IMEI. ${sheetInfo.join('; ')}`);const{error:ae}=await supabase.from('database_versions').update({status:'archived'}).eq('status','active');if(ae)throw ae;const{data:v,error:ve}=await supabase.from('database_versions').insert({file_name:dbFile.name,row_count:rows.length,status:'active'}).select().single();if(ve)throw ve;const batch=500;for(let i=0;i<rows.length;i+=batch){const part=rows.slice(i,i+batch).map(x=>({...x,database_version_id:v.id}));const{error}=await supabase.from('imei_database').insert(part);if(error)throw error}setMsg(`Database berhasil diupload: ${rows.length.toLocaleString()} IMEI unik. ${sheetInfo.join(' · ')}`)}catch(e){setMsg(e.message||String(e))}finally{setBusy(false)}}
async function check(){if(!checkFile)return;setBusy(true);setMsg('Mencocokkan IMEI...');try{const wb=XLSX.read(await checkFile.arrayBuffer());let targetSheet=null,a=null,headerRow=-1,hi=-1;const preferred=wb.SheetNames.find(s=>/5\s*oktober/i.test(s));const candidates=preferred?[preferred,...wb.SheetNames.filter(s=>s!==preferred)]:wb.SheetNames;for(const s of candidates){const rows=XLSX.utils.sheet_to_json(wb.Sheets[s],{header:1,defval:''});for(let r=0;r<Math.min(rows.length,20);r++){const idx=hdr(rows[r]||[],['imei','imei number','imei no','imei no.','imei1']);if(idx>=0){targetSheet=s;a=rows;headerRow=r;hi=idx;break}}if(a)break}if(!a)throw new Error('Kolom IMEI tidak ditemukan pada file pemeriksaan.');const imeis=a.slice(headerRow+1).map(r=>clean(r[hi]));const validImeis=imeis.filter(x=>x);const{data,error}=await supabase.rpc('match_imeis',{p_imeis:validImeis});if(error)throw error;const map=new Map((data||[]).map(x=>[clean(x.imei),x]));const out=[...a];while(out[headerRow].length<9)out[headerRow].push('');out[headerRow][7]='Item Desc';out[headerRow][8]='Model / Variant';let found=0;for(let i=0;i<imeis.length;i++){const x=map.get(imeis[i]);const row=headerRow+1+i;out[row]=out[row]||[];if(x){out[row][7]=x.item_desc;out[row][8]=variant(x.item_desc,x.model_ref);found++}else{out[row][7]=imeis[i]?'TIDAK DITEMUKAN':'';out[row][8]=imeis[i]?'TIDAK DITEMUKAN':''}}const sh=XLSX.utils.aoa_to_sheet(out);const outwb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(outwb,sh,targetSheet);XLSX.writeFile(outwb,`hasil_${checkFile.name}`);setStats({total:validImeis.length,found,missing:validImeis.length-found});setMsg('File hasil berhasil dibuat dan diunduh.')}catch(e){setMsg(e.message||String(e))}finally{setBusy(false)}}
if(!session)return <main><div className="card"><h1>IMEI Matcher</h1><p className="muted">Login admin</p><form onSubmit={login} className="grid"><input placeholder="Username" value={username} onChange={e=>setUsername(e.target.value)} required/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button type="submit">Masuk</button></form>{msg&&<p className="error">{msg}</p>}<p className="muted">Akun admin: username <b>admin</b></p></div></main>;
return <main><div className="row" style={{justifyContent:'space-between',alignItems:'center'}}><div><h1>IMEI Matcher</h1><p className="muted">Login sebagai {role}</p></div><button className="secondary" onClick={logout}>Keluar</button></div>{role==='admin'&&<div className="card"><h2>Update Database IMEI</h2><p className="muted">Upload Excel dengan sheet 1-9 yang memiliki kolom IMEI dan Item Desc.</p><div className="row"><input type="file" accept=".xlsx,.xls" onChange={e=>setDbFile(e.target.files?.[0]||null)}/><button onClick={uploadDb} disabled={busy||!dbFile}>Upload Database</button></div></div>}<div className="card"><h2>Cek IMEI</h2><p className="muted">Kolom IMEI dicocokkan secara exact. Hasil ditulis ke H (Item Desc) dan I (Model / Variant).</p><div className="row"><input type="file" accept=".xlsx,.xls" onChange={e=>setCheckFile(e.target.files?.[0]||null)}/><button onClick={check} disabled={busy||!checkFile}>Cek & Download</button></div>{stats&&<p className="ok">Total: {stats.total.toLocaleString()} · Ditemukan: {stats.found.toLocaleString()} · Tidak ditemukan: {stats.missing.toLocaleString()}</p>}</div>{msg&&<div className="card"><b>Status:</b> {msg}</div>}</main>}